# -*- coding: utf-8 -*-
"""DATASCIENCETASK1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZLVsDoYhNlq7_Oqt785Iq-W8WOUjRWU

IMPORTING NECESSARY LIBRARIES
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

"""LOAD AND READ THE DATASET"""

df=pd.read_csv("/content/IRIS.csv")
df.head()

df.describe()

df.info()

df.shape

df.isna().sum()

df.describe(include ="all")

"""EDA"""

sns.pairplot(df,hue ="species",height = 3.5)
plt.show()

x=df.drop("species",axis=1)
y=df["species"]

"""TRAIN AND TEST THE MODEL"""

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state=42)

"""K NEAREST NEIGHBOR MODEL"""

model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

predictions=model.predict(x_test)

"""ACCURACY AND CLASSIFICATION REPORT"""

accuracy=accuracy_score(y_test,predictions)
report=classification_report(y_test,predictions)
print(f"Accuracy:{accuracy:.2f}")
print("Classification Report:\n",report)

